default:
  bert_base_path: GPT_SoVITS/pretrained_models/chinese-roberta-wwm-ext-large
  cnhubert_base_path: GPT_SoVITS/pretrained_models/chinese-hubert-base
  device: cuda
  is_half: false
  t2s_weights_path: GPT_SoVITS/pretrained_models/s1v3.ckpt
  version: v2
  vits_weights_path: GPT_SoVITS/pretrained_models/s2Gv3.pth
  bigvgan_path: GPT_SoVITS/pretrained_models/models--nvidia--bigvgan_v2_24khz_100band_256x